### PR TITLE
Started initial commit for Beagleboard as well as all of my stuff.

### PR DESCRIPTION
**Pull request by jeid64**

### CODE REVIEW

**Comment by msoucy** [comment]
Could you base it on the `template.md` file, so that the questions are available again?

**Comment by msoucy** [comment]
Never mind, I'll do that now.

**Comment by msoucy** [comment]
Merged, but you should do the rationale - you were the one who advocated for this

**Comment by liam-middlebrook** [comment]
@jeid64 please confirm you see this.

**Comment by jeid64** [comment]
Rationale: We chose the Beaglebone organization as lots of us have used either one of their products or a similar product like the Raspberry Pi. It's a really cool company that has lots of potential for helping people get really cool embedded projects off the ground.

**Pull request merged**
